# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyDemo

  target 'MyDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AFNetworking'
    pod 'STAlertView'
    pod 'Masonry', '~> 1.0.0'
    
  end

  target 'MyDemoUITests' do
    inherit! :search_paths
    # Pods for testing

     pod 'AFNetworking'
    pod 'STAlertView'
  end

end
